# Inventory for Kusala Studio Community Cloud
# AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
---
all:
  children:
    ansible_control:
      hosts:
        localhost:
          ansible_connection: local
    # Add managed node groups here, e.g.:
    # cloud_services:
    #   hosts: {}
